[workspace]
resolver = "3"
members = ["qr-core", "qr-render", "qr-cli", "qr-server"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"
authors = ["Karuna Kiran Bhadra"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/dotmatrixbeeper/qr-generator"

[profile.release]
lto = true