[package]
name = "qr-core"
description = "ISO/IEC 18004-compliant QR code encoder: takes in text input, outputs QR symbol matrix"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
