[package]
name = "qr-cli"
description = "Command-line interface for generating QR codes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "qr"
path = "src/main.rs"

[dependencies]
qr-core = { path = "../qr-core", version = "0.1.0" }
qr-render = { path = "../qr-render", version = "0.1.0" }
clap = { version = "4", features = ["derive"] }